### ISSUE TITLE
Publish binaries as part of the release

### ISSUE THREAD

**Issue by toast-gear** [xelalexv/dregsy#101]
Hello,

I've used this tool before and it's great, I'm in an environment now where using the tool via the published docker images is not possible. I need to download the binary directly onto a machine and use it from there. It would be nice if the binary was published for all the standard arches (GitHub Actions should make that fairly easy, I need x86_64) as part of the release so I don't need to clone the repo, build it and store it myself.

**Comment by xelalexv** [comment]
A set of binaries will be included in releases, starting with `0.5.1`.
