### ISSUE TITLE
Make dregsy crash when the registry is unreachable

### ISSUE THREAD

**Issue by Jonaprince** [xelalexv/dregsy#103]
I'm facing an issue when trying to put a dregsy container as a sidecar in a kubernetes pod for the docker registry in kubernetes. I need synchronize a remote registry with my local but dregsy start faster than the registry container in the pod and the registry can't be synchronized at pod start. It could be great if the container crash when the registry is not reachable so it could restart faster. 

1 - Start pod
2 - Wait for registry container to be up and ready
3 - Start the dregsy sidecar container and clone images into the registry

**Comment by xelalexv** [comment]
Is the intent to only sync once at registry start, or to keep syncing? Also, why do you run dregsy as a sidecar and not a regular pod?

**Comment by xelalexv** [comment]
How about starting the dregsy sidecar container in this way:

```yaml
command: ["/bin/sh"]
args: ["-c", "while ! wget -O - >/dev/null 2>&1 localhost:5000/v2/; do sleep 5; done; dregsy -config={path to config}"]
```

This would wait for the registry endpoint to come up, then start dregsy.
