### ISSUE TITLE
dregsy stopped working sometimes by giving  "exec format error" 

### ISSUE THREAD

**Issue by prasoon-pxc** [xelalexv/dregsy#115]
I have lot of images which I am syncing with dregsy , I am providing configfile using configmap and  running dregsy as a K8s job, but smetimes when I add new image and run this syncer job , it givis me `/usr/local/bin/dregsy: "exec format error" ` error, and after sometimes it started working automatically.

**Comment by xelalexv** [comment]
You usually get this error if you're using a container image for an architecture that doesn't match the architecture of the cluster node. What image are you using, and on what kind of K8s cluster are you seeing this?

**Comment by prasoon-pxc** [comment]
@xelalexv I am using  `xelalex/dregsy` and using `eks 1.29` with below arch of k8s nodes:

```
OS Image:                   Amazon Linux 2
Operating System:           linux
Architecture:               amd64
Container Runtime Version:  containerd://1.7.11
```

**Comment by xelalexv** [comment]
Strange. The official container images I release on DockerHub are amd64 only, so no problem there. Not sure why EKS ends up thinking it's something else. There don't happen to be any ARM nodes in your cluster?

**Comment by prasoon-pxc** [comment]
okay, so we have some spot instance pool also managed my Karpenter and here it is defined both arch:
```
 - key: "kubernetes.io/arch"
          operator: In
          values: [ "arm64", "amd64" ]
```

should I need to set `platform:all` in dregsy config?

**Comment by xelalexv** [comment]
OK, that means that the dregsy k8s job occasionally gets scheduled onto an arm64 node, and then of course fails.

> should I need to set platform:all in dregsy config

That's a config for the images that you sync, not the dregsy image, so it won't help. What you need to do is add a node selector to your dregsy job so that it only gets scheduled to amd64 nodes, e.g (untested):

```yaml
nodeSelector:
    kubernetes.io/arch: amd64
```

**Comment by prasoon-pxc** [comment]
ok thanks @xelalexv
