### ISSUE TITLE
Change the version when synchronizing images

### ISSUE THREAD

**Issue by huangjunxing001** [xelalexv/dregsy#120]
I currently synchronize the image by configuring the yaml file and starting the temporary container, but I want to be able to change the version number of the image while synchronizing the image. Is that possible? And how to edit the configuration file

**Comment by xelalexv** [comment]
If by 'changing the version' you mean changing a tag while synchronizing, then that's not possible. But maybe you could explain what you want to achieve using an example.

**Comment by huangjunxing001** [comment]
As you said, it is impossible to change a label, I get it, thank you for your answer
