### ISSUE TITLE
arm images

### ISSUE THREAD

**Issue by tibeer** [xelalexv/dregsy#121]
Hi!

Are there any plans to also provide arm64 images in the future?

Thanks and kind regards
Tim

**Comment by xelalexv** [comment]
At the moment, you can only cross-compile the dregsy binary for i386, arm, and arm64 with `CROSS=y make dregsy`. You would then have to build an image for ARM, using the created binary (see the existing Dockerfile for reference). In addition you also need to get a Skopeo ARM binary from somewhere though, and include that as well.

**Comment by tibeer** [comment]
Awesome, I will take a look, thank you :)
