### ISSUE TITLE
Tags filtering / skip tags that already exist in the target registry

### ISSUE THREAD

**Issue by yannh** [xelalexv/dregsy#22]
Hello :wave: 

I have implemented some minimal logic for tag filtering: https://github.com/yannh/dregsy#tags-filtering , support for wildcards, comparison operators, and exclude tag ranges.

I have also implemented an option called "skipExistingTags" -  dregsy will skip tags that already exist in the target registry. Since it might cause issues with tags that are not immutable such as 'latest' it is deactivated by default. 

To easily implement both these features, I have removed the docker relay - see https://github.com/xelalexv/dregsy/issues/21

Do you see a path to merge this back here? I am happy to work on clean PRs. But I am not sure how to implement this efficiently using the docker relay :/

Thanks! :+1:

**Comment by yannh** [comment]
:wave: I actually realised that skopeo already supports a sync subcommand that does most of what I m trying to implement here... the yaml format it supports is not fantastic (does not allow to configure the target repository name, for example) but it might be good enough.

**Comment by xelalexv** [comment]
Yes, I was actually thinking to leverage Skopeo's `sync` command for solving issue #16. I also think that the YAML format for `sync` isn't quite stellar, but that would probably not be an issue since we'd be generating it on the fly based on the config of the dregsy sync task. But I haven't looked into it in details yet.

**Comment by mkhodave** [comment]
@xelalexv : can you please give some examples for tag filtering for skopeo sync command  or any plan for add enhancement in dregsy tags field to allow tag filtering ?

**Comment by xelalexv** [comment]
Tag filtering is not yet supported. It's next on my TODO list, but I can't really give you an estimate when that is going to happen.

**Comment by sathieu** [comment]
@mkhodave If you need tag filtering **and** your target is a gitlab instance, take a look at [Gitlabracadabra](https://gitlab.com/gitlabracadabra/gitlabracadabra/-/blob/master/doc/image_mirrors.md).

I plan to implement other destinations in the future.

**Comment by mkhodave** [comment]
@sathieu : my target is google artifact registry , does tag filtering mentioned in [Gitlabracadabra](https://gitlab.com/gitlabracadabra/gitlabracadabra/-/blob/master/doc/image_mirrors.md) also can be used in my use case ?

**Comment by mkhodave** [comment]
@xelalexv & @sathieu : Thanks for quick reply, really helpful for planning task around Google artifact registry

**Comment by xelalexv** [comment]
And here goes regex support for tag filtering. It uses standard _Golang_ regular expressions, same as image mapping. Expanding on above example, you can now do:
```
tags:
    - "semver: >=1.31.0 <1.31.9"
    - "regex: 1\.26\.[0-9]-(glibc|uclibc|musl)"
    - "1.29.4"
    - "latest"
```
This would additionally sync any `1.26.`x image with suffix `-glibc`, `-uclibc`, or `-musl`. I updated the `issue22` image over at _DockerHub_.
