### ISSUE TITLE
bump skopeo version

### ISSUE THREAD

**Issue by callum-tait-pbx** [xelalexv/dregsy#29]

**Comment by sathieu** [comment]
Currently it's [pinned to 0.2.0-r1](https://github.com/xelalexv/dregsy/blob/505879b/hack/dregsy.Dockerfile#L23) (9 Apr 2020). Latest is [1.2.1](https://github.com/containers/skopeo/releases).

**Comment by xelalexv** [comment]
Correct, but that's what's available via `apk` in Alpine 3.12.x. For upgrading Skopeo to 1.2.1, we first need to upgrade Alpine to 3.13.x.

**Comment by xelalexv** [comment]
released with 0.3.5
