### ISSUE TITLE
Exit success on failure instead of exit failure

### ISSUE THREAD

**Issue by shoeper** [xelalexv/dregsy#3]
Currently when an image is not available the program aborts with access success. Could the exit code be changed to non zero?

**Comment by xelalexv** [comment]
Exit code is now set to `1` in case any problems occurred while handling the defined sync tasks. More precisely, if the most recent invocation of any task failed, dregsy reports `1` when exiting. For one-off tasks, there obviously is only one invocation. If that fails, exit code is `1`. If for a recurring task, one or more failed invocations are followed by a successful one, then this is not considered an error. This will mask intermittent failures.

Note that dregsy does not stop when a task fails. So if there's at least one recurring task, dregsy will run indefinitely until interrupted. It will then report an exit code as outlined above.

**Comment by shoeper** [comment]
Great!
