### ISSUE TITLE
Use GCR without auth?

### ISSUE THREAD

**Issue by zvickery** [xelalexv/dregsy#37]
Hi, I'd like to synch some public repos from GCR.  An example being `k8s.gcr.io/autoscaling/vpa-admission-controller`.

It seems like the current implementation of dregsy requires me to provide project credentials because the registry has `gcr.io` in the name.  This isn't necessary and I would like to avoid it.  Is there any way to do this that I am missing?

If not, I'm willing to make a PR to address this.  Perhaps the code could proceed without GCR credentials and treat the lack thereof as a warning and not an error?

**Comment by xelalexv** [comment]
Thanks for the report! Yes, currently that's the behaviour, which of course is problematic for public images on GCR. I've created a fix in branch `issue37`, maybe you can try that out. You will have to set `auth: none` in the source of your task. With this, dregsy will not do any authentication in case of GCR. There's also an according image on DockerHub, tagged `issue37`.

**Comment by zvickery** [comment]
Thank you for the quick turnaround.  The new image works great for me!

**Comment by xelalexv** [comment]
merged with PR #38
