### ISSUE TITLE
Provide a non-alpine image?

### ISSUE THREAD

**Issue by callum-tait-pbx** [xelalexv/dregsy#47]
I would like to use your docker container with the aws cli so I can perform a ECR login with role based auth. I think this would be a pretty common use case for this tool. Unfortunately AWS do not provide a binary which will work on docker images based on Alpine because they're compiling them against glibc. Hacking this into an alpine image is very cumbersome and not very easy to document https://github.com/aws/aws-cli/issues/4971 https://github.com/aws/aws-cli/issues/4685

It would be great if we could get a non-alpine based image for people wanting to use your tool with AWS.

**Comment by xelalexv** [comment]
I've prepared an Ubuntu 20.04 based dregsy image. I hope that that can fulfill most user's requirements. For 20.04, Skopeo is not yet in the official repos, but I wanted to stick with an LTS release. So Skopeo gets installed via the [Kubic project](https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/skopeo), as per Skopeo's documentation. This gives us Skopeo 1.2.2 for Ubuntu, vs 1.2.1 for Alpine. I'd prefer the same version, but Kubic doesn't seem to keep older package versions around.

Both variants get tested before a release (`Makefile` is adapted accordingly). Starting with the next release, three tags will get published for each release: `{version}-ubuntu`, `{version}-alpine`, and `{version}`, with the latter two referring to the same image. The same will be done for `latest`. I've just pushed `latest-ubuntu` and `latest-alpine` already, so you can try out.

**Comment by xelalexv** [comment]
added with version 0.3.6
