### ISSUE TITLE
Error syncing entire namespace

### ISSUE THREAD

**Issue by sjthespian** [xelalexv/dregsy#57]
I have set up a namespace in my Quay registry that I want to sync to a remote Nexus3 registry. Things work fine if I specify a specific repo in my source registry, but not if I specify a namespace or a regex into that namespace.

For example, this:
```yaml
    mappings:
      - from: regex:sync/.*
        to: regex:sync/(.*),synctest-$1
```
give me this error:
```
ERRO[0000] error getting catalog page: GET https://registry.xxxxxx.com/v2/auth?scope=registry%3Acatalog%3A%2A&service=registry.xxxxxx.com: INVALID_REQUEST: Unable to decode repository and actions: registry:catalog:*; map[]
```

If I change the mapping to:
```
    mappings:
      - from: sync/alpine
        to: regex:sync/(.*),synctest-$1
```
It will sync the alpine repo correctly.

Any idea what might be going on? I am assuming this has something to do with the way Quay is responding to the wildcard request, but want to make sure before I go open a ticket with RedHat.

I am using a local build of dregsy built from the master branch in GitHub and skopeo 1.4.1.

**Comment by xelalexv** [comment]
I assume you're using the default [lister type](https://github.com/xelalexv/dregsy/blob/master/doc/design-image-matching.md), i.e. `catalog`. I'm not sure whether *Quay* fully supports this. If so, the error you're seeing may be related to authentication/authorization. Could you attach a bit more log context at debug level?

**Comment by sjthespian** [comment]
I tried the `dockerhub` and `index` lister types, no luck at all with those. I would be surprised if it is authentication, since it works fine if I give it a specific repo name.

There isn't a lot of info from the debug logs:
```
❯ LOG_LEVEL=debug _build/bin/dregsy --config shipsync.yml | tee sync.out
time="2021-09-20T08:23:35-07:00" level=info msg="dregsy 0.4.1-dirty"
time="2021-09-20T08:23:35-07:00" level=debug msg="lister max items set to 100"
time="2021-09-20T08:23:35-07:00" level=debug msg="lister cache duration set to 1h0m0s"
time="2021-09-20T08:23:36-07:00" level=info msg="skopeo version 1.4.1\n"
time="2021-09-20T08:23:36-07:00" level=info msg="relay ready" relay=skopeo
time="2021-09-20T08:23:36-07:00" level=debug msg="task starts ticking" task=sync-lab
time="2021-09-20T08:23:36-07:00" level=debug msg="sending initial fire" task=sync-lab
time="2021-09-20T08:23:36-07:00" level=info msg="waiting for next sync task..."
time="2021-09-20T08:23:36-07:00" level=info msg="syncing task" source=registry.xxxxxx.com target="regstry1.xxxxxx.com:8083" task=sync-lab
time="2021-09-20T08:23:36-07:00" level=info msg=mapping from="regex:sync/.*" to="regex:sync/(.*),synctest-$1"
time="2021-09-20T08:23:36-07:00" level=info msg="refreshing credentials" registry=registry.xxxxxx.com
time="2021-09-20T08:23:36-07:00" level=info msg="refreshing credentials" registry="registry1.xxxxxx.com:8083"
time="2021-09-20T08:23:36-07:00" level=debug msg="retrieving repository list"
time="2021-09-20T08:23:36-07:00" level=debug msg="registry scheme = https"
time="2021-09-20T08:23:37-07:00" level=error msg="error getting catalog page: GET https://registry.xxxxxx.com/v2/auth?scope=registry%3Acatalog%3A%2A&service=registry.xxxxxx.com: INVALID_REQUEST: Unable to decode repository and actions: registry:catalog:*; map[]"
time="2021-09-20T08:23:37-07:00" level=info msg="waiting for next sync task..."
```

**Comment by xelalexv** [comment]
Authorization wise the ability to pull is not necessarily the same as the ability to access the catalog. Some background: The pull API of registries can only handle exact image references, and does not understand wildcards, regexes and the like. Therefore dregsy first needs to get a list of the repos/images, filter that with the given regex, and sync the remaining items from the list one by one. It's the first step in this process that fails, i.e getting the catalog page. Now this *may* be related to authentication, but could also have other reasons. Unfortunately I'm not at all familiar with Quay, so I first need to do some research about its support for the `catalog` API.

**Comment by sjthespian** [comment]
Let me see what I can dig up as well. Quay as two APIs -- the "standard" docker API and their own registry API. It wouldn't surprise me if they only support wildcards via. their API and/or it requires an API key instead of the user authentication. I've done some API work against it in the past, but it has been a few years.

**Comment by sjthespian** [comment]
I have yet to figure out a way to authenticate to Quay in such a way that I can sync all repos. However, this is something of a moot point, as I ended having to write a python app to auto-generate my configuration anyway. Quay only supports a single level in their namespaces, while the repos that I am syncing to all support hierarchical namespaces. So if I have something like `myregistry.example.com/syncimages/foo:1.0`in Quay, that might end up mapping to `registry1.example.com/big/bang/foo:1.0` in the destination registry. And `syncimages/bar:1.1` might map to some completely different namespace.

I have a feeling that in the long run I may end up just abandoning Quay and using one of our Nexus repos instead.

**Comment by xelalexv** [comment]
Is this still an issue, or can we close this?

**Comment by xelalexv** [comment]
Please reopen if there's still an issue left.
