### ISSUE TITLE
Add command line flag to limit tasks

### ISSUE THREAD

**Issue by sjthespian** [xelalexv/dregsy#59]
I have a dregsy yaml file that syncs to 5 different docker registries. From time to time, I would like to be able to run a manual sync to just one or two of them w/o having to extract that data to a separate yaml file. It would be very useful to be able to specify which tasks to run from the command line. I'm thinking something along the lines of what anisble-playbook uses:
`dregsy --config regsync.yml --limit sync-registry2`

**Comment by xelalexv** [comment]
Interesting. I see how that could be handy. We could go for two complementary flags though, `--select` and `--deselect`, or alternatively `--include`/`--exclude`. Not sure yet which one is better.

In the meantime, you could use `yq` to filter your config file, e.g.:

```bash
# include all test-* tasks
yq eval 'del(.tasks.[] | select(.name != "test-*"))' dregsy.yaml

# exclude all test-* tasks
yq eval 'del(.tasks.[] | select(.name == "test-*"))' dregsy.yaml
```

There should be an expression with only `select`, but I couldn't figure out how to do that just now.

**Comment by rubin55** [comment]
What about `--task` which if not specified simply does all tasks defined in the configuration file, but can be specified multiple times to select tasks to run, like:

```shell
$ dregsy --config my_config_with_many_tasks.yaml --task foo --task bar --task baz
```

**Comment by xelalexv** [comment]
I finally settled on `-run {regexp}`, similar to `go test -run {regexp}`. This selects the tasks to be run. Only difference to `go test` is that here the expression already does a line match, so you don't need to place the expression in `^...$` to get an exact match. For example, `-run=task-a` will only select `task-a`, but not `task-abc`.

**Comment by xelalexv** [comment]
done with PR #76
