### ISSUE TITLE
No output from skopeo, even with increased logging

### ISSUE THREAD

**Issue by der-eismann** [xelalexv/dregsy#80]
Hey, first of all thank you for this project!
We hit the docker rate limit today, but it took us a while to figure it out because there were no logs from Skopeo shown, even with increased logging. All we got was output like this:
```
time="2022-07-29T09:14:10Z" level=info msg=mapping from=/busybox to=/busybox
time="2022-07-29T09:14:10Z" level=info msg="refreshing credentials" registry=docker.io
time="2022-07-29T09:14:10Z" level=info msg="refreshing credentials" registry=12345678910.dkr.ecr.eu-west-1.amazonaws.com
time="2022-07-29T09:14:10Z" level=info msg="target already exists" ref=12345678910.dkr.ecr.eu-west-1.amazonaws.com/busybox
time="2022-07-29T09:14:10Z" level=info msg="syncing tag" platform=all tag=latest
time="2022-07-29T09:14:50Z" level=error msg="exit status 1"
time="2022-07-29T09:14:50Z" level=error msg="errors during sync"
```

Only when I modified [these lines](https://github.com/xelalexv/dregsy/blob/master/internal/pkg/relays/skopeo/skopeo.go#L155-L156) to `os.Stdout` & `os.Stderr` I was able to see the Skopeo output. It's too much to show the user everything, but maybe it's better to buffer the output and print it if there was an error? We felt a bit mocked when it said "something failed, but I won't tell you what" :smile:

**Comment by xelalexv** [comment]
Could you try setting `verbose: true` for the task in question? That should produce the desired output.

**Comment by der-eismann** [comment]
Thanks for the quick reply! Completely overlooked this one - maybe it makes sense to add a hint [in the logging section](https://github.com/xelalexv/dregsy#logging) that verbose logging can be enabled per job?
