### ISSUE TITLE
Split config and credentials/secrets

### ISSUE THREAD

**Issue by deimosfr** [xelalexv/dregsy#93]
Hi,

Is there any way to split configuration and secrets form the config.yaml?

Basically, I would like to share against my team the configuration file but not secrets.

If it's not possible would you be open for a pull request?

Thanks

**Comment by xelalexv** [comment]
You could use `${...}` style variables in the config file, and use `envsubst` (either standard from package repos, or [this one](https://github.com/a8m/envsubst) for more options) to replace during deployment, while secrets are present in environment.

**Comment by deimosfr** [comment]
That's an option I was thinking too. Thanks for the answer
